### ISSUE TITLE
Fix the Silly fxml Null Error

### ISSUE THREAD

**Issue by james-garrett** [UQdeco2800/minesim#12]
A rather simple bug, the fxml loader is getting a null pointer error because something in the call statement is probably wrong.
![waaaaa](https://cloud.githubusercontent.com/assets/9358458/11337472/fcc025ca-9238-11e5-9ff8-68e370b9ac5e.png)

**Comment by cavejay** [comment]
Do you have any idea how to recreate this bug @james-garrett? I'm not sure how to start without actually seeing it happen.

**Comment by james-garrett** [comment]
When I run minesim in my IDE (picking Minesim.java as the target for running) I always get this error.

**Comment by cavejay** [comment]
O.o why are you picking a target to run? you should always be using `gradle run`

**Comment by james-garrett** [comment]
Because running it in IntelliJ gives more details on why things go wrong. It helped me stomp a bunch of testing errors out.

**Comment by cavejay** [comment]
you can do that through intellij as well. 
There should be a gradle pane or something in the intellij UI that lists all the valid gardle commands. one of them is gradle run

**Comment by james-garrett** [comment]
I can do that, but I'm concerned as to why this error is appearing. It totally could be  IDE-specific...

**Comment by cavejay** [comment]
So I've replicated this issue, but because `gradle run` is the only supported run system for this project I don't think it's something we should concern ourselves with. 
Maybe @timmyhadwen could confirm but gradle most likely sets up some of the environment that the project requires (such as resources and the like) which is why running the main of the whole game fails without the proper setup.

**Comment by timmyhadwen** [comment]
Defiantly gradle pls
